image: atlassian/default-image:4

pipelines:
  default:
    main:
    - step:
        name: Install dependencies
        script:
          - npm install
          - npm install -g aws-cli
        services: 
          - mysql 

definitions: 
  services: 
    mysql: 
      image: mysql:5.7 
      variables: 
        MYSQL_DATABASE: 'pipelines'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes' 
        MYSQL_USER: 'test_user'
        MYSQL_PASSWORD: 'test_user_password'