image:
  name: hashicorp/terraform  # Use Terraform image

pipelines:
  branches:
    main:  # Define pipeline for the main branch
      - step:
          name: Install NodeJS
          caches:
            - node
          script:
            - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            - node --version
            # install all pkgs in one command
            - sudo apt install -y nodejs docker.io openjdk-8-jdk

              #### for Docker - required
            - sudo usermod -aG docker $USER # current user must have a group call docker.
            - sudo chown $USER:docker /var/run/docker.sock # docker.sock file must have current user's onwership.
            - sudo chmod 666 /var/run/docker.sock # change the permission too.

      - step:
          name: Install Dependencies
          caches:
            - node
          script:
            - npm install  # Install Node.js dependencies
            - npm install -g aws-cli  # Install AWS CLI for deployment
            - npm install --save-dev jest @jest/globals pg
            
      - step:
          name: Deploy Infrastructure
          caches:
            - node
          script:
            - cd terraform  # Navigate to Terraform directory
            - # create ssh key for terraforming.
            - ssh-keygen -f my_demo_key
              # download the required provider or packages.
            - terraform init
              # deploy your infrastructure and approve automatically.
            - terraform apply -auto-approve
              # remove infrastructure from aws once you are done.
            - terraform destroy -auto-approve
            
      - step:
          name: Run Tests
          caches:
            - node
          script:
            - npx jest   # Run Jest tests for database
            
      - step:
          name: Destroy Infrastructure
          caches:
            - node
          script:
            - cd terraform  # Navigate to Terraform directory
            - terraform destroy -auto-approve  # Destroy Terraform resources after testing
