name: CI

on: [push]

env:
  AWS_REGION : "eu-west-1"


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Terraform Init
      working-directory: ./Infrastructure
      run: terraform init
    
    - name: Terraform Plan
      working-directory: ./Infrastructure
      run: terraform plan -out=tfplan
    
    - name: Terraform Apply
      working-directory: ./Infrastructure
      run: terraform apply -auto-approve tfplan